# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmojibleIOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmojibleIOS
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'

  target 'EmojibleIOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EmojibleIOSUITests' do
    # Pods for testing
  end

end
