from enum import Enum
class TokenType(Enum):
    INTEGER = 'INTEGER'
    REAL = 'REAL'
    INTEGER_CONST = 'INTEGER_CONST'
    REAL_CONST = 'REAL_CONST'
    PLUS = 'PLUS'
    MINUS = 'MINUS'
    MUL = 'MUL'
    INTEGER_DIV = 'INTEGER_DIV'
    FLOAT_DIV = 'FLOAT_DIV'
    LPAREN = 'LPAREN'
    RPAREN = 'RPAREN'
    ID = 'ID'
    ASSIGN = 'ASSIGN'
    BEGIN = 'BEGIN'
    SEMI = 'SEMI'
    DOT = 'DOT'
    PROGRAM = 'PROGRAM'
    VAR = 'VAR'
    COLON = 'COLON'
    COMMA = 'COMMA'
    EOF = 'EOF'